```{r}

library(ggplot2) #must load the ggplot package first
dm = data(diamonds) #loads the diamonds data set since it comes with the ggplot package
```

quiz 1
```{r}
summary(diamonds)
nrow(diamonds)
ncol(diamonds)
by( diamonds$cut,diamonds$color,summary)
?diamonds
```

quiz 2
```{r}
ggplot(aes(x = price), data = diamonds)+
  geom_histogram()
```
quiz 4
```{r}
sum(diamonds$price<500)
sum(diamonds$price<250)
sum(diamonds$price>=15000)
```
quiz 5
```{r}
ggplot(aes(x = price), data = diamonds)+
  geom_histogram()+
  scale_x_log10(limits = c (250,15000))
ggsave('dimondpriceshistogram.png')
```
quiz 6
```{r}
ggplot(aes(x = price), data = diamonds)+
  geom_histogram()+
  scale_x_continuous(limits = c (250,15000))+
  facet_wrap(~cut)

```

quiz 7
```{r}
by(diamonds$price,diamonds$cut,max)
```
quiz 8

```{r}
qplot(x = price, data = diamonds) + facet_wrap(~cut,scales = "free_y")
?facet_wrap

```
quiz 9
```{r}
ggplot( aes(x= price/carat), data = diamonds)+
  geom_histogram()+
  scale_x_log10()+
  facet_wrap(~cut, scales = "free_y")
```
quiz 10
```{r}
qplot(x = clarity,y = price,  data = diamonds,geom = "boxplot")
qplot(x = cut,y = price,  data = diamonds,geom = "boxplot")
qplot(x = color,y = price,  data = diamonds,geom = "boxplot")
  
```

quiz 11
```{r}
by(diamonds$price, diamonds$color,summary)
IQR(diamonds[diamonds$color == 'J',]$price)

```

quiz 12
```{r}
qplot(x = color, y = price/carat, data = diamonds,geom = 'boxplot')

```

quiz 13
```{r}
qplot(x= carat, data = diamonds, geom = 'freqpoly',binwidth = 0.01)+
  scale_y_continuous(breaks = seq(0,10000,2000))

table(diamonds$carat)[table(diamonds$carat)>2000]


```

quiz 15
```{r}
library(readxl)
library(tidyr)
womenmarriage =  read_excel("indicator age of marriage.xlsx", na = "NA" )
names(womenmarriage)[1] = "Country"
df <- gather(womenmarriage,"year","n",2:ncol(womenmarriage))
df$year=as.integer(df$year)
head(df)
remove_missing(df)
```


